---
title: "strings_and_factors"
author: "Bohan Zhu"
date: "2025-10-23"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, tidy = TRUE)
```

```{r}
library(tidyverse)
library(rvest)
```

```{r, include=FALSE}
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%",
  fig.retina = 2,
  dpi = 320
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


## Mostly use string vectors

```{r}
string_vec= c("my","name","is","Bohan")

str_detect(string_vec,"Bohan")
str_detect(string_vec,"e")
str_detect(string_vec,"Zhu")

str_replace(string_vec,"Bohan","Bohan Zhu")

str_replace(string_vec,"e", "")
str_remove(string_vec,"e")
```

```{r}
string_vec = c(
  "i think we all rule for participating",
  "i think i have been caught",
  "i think this will be quite fun actually",
  "it will be fun, i think"
  )

str_detect(string_vec, "^i think") #start from I think
str_detect(string_vec, "i think$") #end with I think

str_remove(string_vec,"i think$")
```

```{r}
string_vec = c(
  "Time for a Pumpkin Spice Latte!",
  "went to the #pumpkinpatch last weekend",
  "Pumpkin Pie is obviously the best pie",
  "SMASHING PUMPKINS -- LIVE IN CONCERT!!"
  )

str_detect(string_vec,"[Pp]umpkin")
```

Let's get a bit more complicated.

```{r}
string_vec = c(
  '7th inning stretch',
  '1st half soon to begin. Texas won the toss.',
  'she is 5 feet 4 inches tall',
  '3AM - cant sleep :('
  )

str_detect(string_vec, "^[0-9][a-zA-Z]") 
```

```{r}
string_vec = c(
  'Its 7:11 in the evening',
  'want to go to 7-11?',
  'my flight is AA711',
  'NetBios: scanning ip 203.167.114.66'
  )

str_detect(string_vec, "7.1") #want to find 7 followed by 1
#if we want to see just .1
str_detect(string_vec, "7\\.1") 
```

```{r}
string_vec = c(
  'The CI is [2, 5]',
  ':-]',
  ':-[',
  'I found the answer on pages [6-7]'
  )

str_detect(string_vec, "\\[")
```



## Factros

```{r}
vec_sex = factor(c("male", "male", "female", "female"))
vec_sex
```

```{r}
as.numeric(vec_sex)
```

```{r}
vec_sex = fct_inorder(vec_sex)
vec_sex #we make male as the reference
```



## Revisit NSDUH
```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"
```

```{r}
drug_use_html = read_html(url)

ndsuh_df = 
  drug_use_html |> 
  html_table() |> 
  first() |> 
  slice(-1)
```

Now do the tidying
```{r}
marj_df = 
  ndsuh_df |>
  select(-contains("P Value")) |>
  pivot_longer(
    -State,
    names_to = "age_year", 
    values_to = "percent") |> 
  separate(age_year, into = c("age", "year"), sep = "\\(") |>
  mutate(
    year = str_replace(year, "\\)", ""),
    percent = str_replace(percent, "[a-c]$", ""),
    percent = as.numeric(percent)) |>
  filter(!(State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West")))
```

Let's make quick plot
```{r}
marj_df |>
  filter(age == "12-17") |> 
  mutate(State = fct_reorder(State, percent)) |> 
  ggplot(aes(x = State, y = percent, color = year)) + 
    geom_point() + 
    theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

## Restaurant Inspections!

```{r}
library(p8105.datasets)
data("rest_inspec")
```

```{r}
rest_inspec = 
    rest_inspec |> 
    rename(borough = boro)

rest_inspec |> 
  group_by(borough, grade) |> 
  summarize(n = n()) |> 
  pivot_wider(
    names_from = grade,
    values_from = n)
```

Update the dataset

```{r}
rest_inspec =
  rest_inspec |> 
  filter(
    grade %in% c("A", "B", "C"),
    borough !=0)
```

Look for pizza places 

```{r}
rest_inspec |> 
  filter(str_detect(dba, "Pizza")) |> 
  group_by(borough, grade) |> 
  summarize(n = n()) |> 
  pivot_wider(
    names_from = grade,
    values_from = n)
```

```{r}
rest_inspec |> 
  filter(str_detect(dba, "[Pp][Ii][Zz][Zz][Aa]")) |> 
  group_by(borough, grade) |> 
  summarize(n = n()) |> 
  pivot_wider(
    names_from = grade,
    values_from = n)
```

Let's make this table a plot instead

```{r}
rest_inspec |> 
  filter(str_detect(dba, "[Pp][Ii][Zz][Zz][Aa]")) |> 
  mutate(borough = fct_infreq(borough)) |> 
  ggplot(aes(x = borough, fill = grade)) +
  geom_bar()
```

This doesn't work as I wanted
```{r}
rest_inspec |> 
  filter(str_detect(dba, "[Pp][Ii][Zz][Zz][Aa]")) |> 
  mutate(
    borough = fct_infreq(borough),
    borough = str_replace(borough, "Manhattan", "The City")) |>   
  ggplot(aes(x = borough, fill = grade)) +
  geom_bar()
```

but this does. 
```{r}
rest_inspec |> 
  filter(str_detect(dba, "[Pp][Ii][Zz][Zz][Aa]")) |> 
  mutate(
    borough = fct_infreq(borough),
    borough = fct_recode(borough, "The city" = "Manhattan")
    )|>   
  ggplot(aes(x = borough, fill = grade)) +
  geom_bar()
```

